config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :destroy, :edit, :update]
  get 'users/:id/reservation', to: 'users#reservation', as: :user_reservation
  resources :pets, only: [:create, :new, :destroy, :index, :show, :edit, :update] do
    resources :reservations, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      member do
        patch 'accept', to: "reservations#accept"
        patch 'reject', to: "reservations#reject"
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  CATEGORY = %w[Dog Cat Bird Reptile Rodent]
  has_many :reservations
  belongs_to :user
  has_many_attached :photos
  validates :name, presence: true
  validates :age, presence: true
  validates :species, presence: true
  validates :breed, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  validates :pet, uniqueness: { scope: :start_date }
  validates :pet, uniqueness: { scope: :end_date }
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :pets, dependent: :destroy
  has_many :received_reservations, through: :pets, source: :reservations
  has_many :sent_reservations, class_name: "Reservation"
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]
  def index
    if params[:query].present?
      @busqueda = params[:query].capitalize
      if Pet::CATEGORY.include?(@busqueda)
        @pets = policy_scope(Pet.where(species: @busqueda))
      else
        @pets = policy_scope(Pet)
      end
    else
      @pets = policy_scope(Pet)
    end
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @user = current_user.id
    @pet.user_id = @user
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def update
    authorize @pet
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    authorize @pet
    @pet.destroy
    redirect_to user_path, notice: "Your pet was removed"
  end

  private

  def set_pet
    @pet = authorize Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :age, :species, :breed, :description, photos: [])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :destroy, :update, :edit, :accept, :reject]
  def index
    @reservations = policy_scope(Reservation)
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @reservation = Reservation.new
    authorize @reservation 
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @user = current_user
    @reservation = Reservation.new(reservation_params)
    @reservation.user = @user
    @reservation.pet = @pet
    authorize @reservation
    if @reservation.save
      redirect_to user_path(@user, tab: "new-pet-requests"), notice: "Congratulation 🎉 Your reservation was successful"
    else
      render :new
    end
  end

  def show
    @pet = Pet.find(params[:pet_id])
  end

  def update
    @reservation.update(reservation_params)
    redirect_to reservation_path(@reservation)
  end

  def destroy
    @reservation.destroy
    redirect_to users_path
  end

  def accept
    @reservation.accepted!
    @user = current_user
    authorize @reservation
    redirect_to user_path(@user, tab: "borrow-requests")
  end

  def reject
    @reservation.rejected!
    @user = current_user
    redirect_to user_path(@user, tab: "borrow-requests")
  end

  private

  def set_reservation
    @reservation = authorize Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = authorize User.find(params[:id])
    @pets = @user.pets
    @reservations = Reservation.all
  end

  def edit
    @user = authorize User.find(params[:id])
  end

  def update
    @user = authorize User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def reservation
    @user = authorize User.find(params[:id])
  end

  def destroy
    @user = authorize User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petmate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class='home-container'>
<%= render 'shared/banner' %>
<%= render 'shared/footer' %>
</div>

app/views/pets/_form.html.erb
<h1>Update</h1>
<h2>
  <%= simple_form_for(@pet) do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :species %>
    <%= f.input :breed %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</h2>

app/views/pets/edit.html.erb
<h1>Edit</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
        <div class="col col-md-8 col-lg-10">
          <div class="container-form-int">
            <%= render "form", pet: @pet %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-11">
    <h2 class="mt-5">Browse with sweetness the <%= @pets.count %> available pets</h2>
      <div class = "cards">
        <% @pets.each do |pet| %>
          <a href="<%= pet_path(pet)%>">
            <div class = "card card-index" style = "height: 350px" >
              <% if pet.photos.attached? %>
                <div class="card-image" style="background-image: url('<%= cl_image_path pet.photos[0].key %>')"></div>
              <% else %>
                <div class="card-image" style="background-image: url('')"></div>
              <% end %>
              <div class = "card-description" >
                <h2><%= pet.name %></h2>
                <p>Breed: <%= pet.breed %></p>
                <p>Age: <%= pet.age %></p>
              </div>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
         
          <div class="container-form-int">
            <%= simple_form_for [@pet] do |f|   %>
              <%= f.input :name , label: 'Name of the pet'%>
              <%= f.input :age , label: 'Age of the pet'%>
              <%= f.input :species , label: 'Species of the pet', collection: Pet::CATEGORY %>
              <%= f.input :breed , label: 'breed of the pet'%>
              <%= f.input :description , label: 'description of the pet'%>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
              <%= f.button :submit, "Submit", class: "btn-pink"  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<h2 class="pet-title m-4"><%= @pet.name %></h2>

<div class="d-flex mt-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <div class="cards m-2">
          <% @pet.photos.each do |photo| %>
          <div class="card-category" style="background-image: url(<%= cl_image_path(photo.key) %>)"></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-description">
        <div class="col-cards">
          <h4>🐾 Owner:</h4>
          <p class="pet-details px-4"> <%= @pet.user.first_name %> <%= @pet.user.last_name %> </p>
        </div>
        <div class="col-cards">
          <h4>🐾 Breed:</h4>
          <p class="pet-details px-4"> <%= @pet.breed %> </p>
        </div>
        <div class="col-cards">
          <h4>🐾 Species:</h4>
          <p class="pet-details px-4"> <%= @pet.species %> </p>
        </div>
        <div class="col-cards">
          <h4>🐾 Age:</h4>
          <p class="pet-details px-4"> <%= @pet.age %> years old. </p>
        </div>
        <div class="col-cards">
          <h4>🐾 Description:</h4>
          <div><p class="pet-details px-4"> <%= @pet.description %></p></div>
        </div>
        <div class="d-flex justify-content-center">
          <% if policy(@pet).edit? %>
            <h2 class="m-3"><%= link_to 'Edit', edit_pet_path(@pet), class: "btn btn-outline-warning" %></h2>
          <% end %>
          <% if policy(@pet).destroy? %>
            <h2 class="m-3"><%= link_to 'Remove', pet_path(@pet), class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></h2>
          <% end %>
          <% if policy(@pet).rent? %>
            <h2 class="m-3"><%= link_to 'Rent', new_pet_reservation_path(@pet), class: "btn btn-flat-orange", style: "width: 150px;"%></h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/update.html.erb
<h1>Update</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
        <div class="col col-md-8 col-lg-10">
          <div class="container-form-int">
            <%= render "form", pet: @pet %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/_form.html.erb
<h2>
  <%= simple_form_for [@pet, @reservation] do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.submit %>
  <% end %>
</h2>

app/views/reservations/edit.html.erb
<h1>Edit</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
        <div class="col col-md-8 col-lg-10">
          <div class="container-form-int">
            <%= render "form", reservation: @reservation %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class = "cards">
        <% @reservations.each do |reservation| %>
          <div class = "card" >
            <div class="card-image" style="background-image: url(<%= cl_image_path reservation.pet.photos[0].key %>)">
            </div>
            <div class = "card-description">
              <h2><%= reservation.pet.name %></h2>
              <p>Rented from <%= reservation.start_date %> - <%= reservation.end_date%></p>
              <div class="card-action">
                <h2><%= link_to 'Show', pet_reservation_path(reservation.pet, reservation) %></h2>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <% if policy(Reservation).create? %>
          <%= link_to "New reservation", new_pet_reservation_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
        <div class="container">
          <div class = card>
            <div class="card-image" style="background-image: url(<%= cl_image_path pet.photos[0].key %>)">
            </div>
            <div class = "card-description">
              <h2><%= @pet.name %></h2>
              <p>Rented from <%= @reservation.start_date %> - <%= @reservation.end_date%></p>
              <div class="card-action">
                  <% if policy(@reservation).edit? %>
                    <h2><%= link_to 'Edit', edit_pet_reservation_path(@reservation) %></h2>
                  <% end %>
                  <% if policy(@reservation).destroy? %>
                    <h2><%= link_to 'Destroy', pet_reservation_path(@reservation), method: :delete, data: { confirm: 'Are you sure?' } %></h2>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/update.html.erb
<h1>Update</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
        <div class="col col-md-8 col-lg-10">
          <div class="container-form-int">
            <%= render "form", reservation: @reservation %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="row justify-content-md-left m-0">
    <div class="col col-sm-10 col-md-6 col-lg-6 m-0">
      <div class = "container-home-page">
        <h1>Petmate brings you closer to your new <strong> best friend</strong>!</h1>
        <p>Make the world happier one pet at a time</p>
        <%= form_tag pets_path, method: :get do %>
          <div class="search-form-control form-group">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Species of your new friend"
            %>
            <%= submit_tag "Search", class: "btn btn-flat-orange" %>
          </div>
        <% end %>
        <div class="mt-2">
        <%= link_to "Or click here to see all the available pets!", pets_path, class: "btn btn-flat-orange" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>

      <%= image_tag '/avatar_dog.png' %>
    <% end %>

    <h2 class="navbar-title-website">Petmate</h2>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add pets", new_pet_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List of pets", pets_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key.nil?%>
            <%= image_tag '/cat-icon.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: 45, height: 45 %>
            <% else%>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false,
            width: 45, height: 45, crop: :thumb, gravity: :face, zoom: 0.7, radius: :max %>
            <% end%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile page", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_card.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
        <div class="container">
          <div class = card>
            <div class="card-image" style="background-image: url(<%= cl_image_path pet.photos[0].key %>)">
            </div>
            <div class = "card-description">
              <h2>You're a reservation with <%= @pet.name %></h2>
              <p><%= @reservation.start_date %> - <%= @reservation.end_date %></p>
              <div class="card-action">
                  <% if policy(@reservation).edit? %>
                    <h2><%= link_to 'Edit', edit_pet_path(@pet) %></h2>
                  <% end %>
                  <% if policy(@reservation).destroy? %>
                    <h2><%= link_to 'Destroy', reservation_path(@reservation), method: :delete, data: { confirm: 'Are you sure?' } %></h2>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/reservation.html.erb
<section class="tabs-container">
   <label for="tab1"> Profile </label>
   <label for="tab2"> My reservations </label>
   <label for="tab3"> Third Tab </label>
</section>

<input name="tab" id="tab1" type="radio" checked />
<section class="tab-content">
  <div class="user-banner">
  <% if @user.photo.key.nil?%>
  <%= image_tag "cat-icon.png",
  width: 150, height: 150, style: "border-radius: 50%" %>
  <% else%>
  <%= cl_image_tag @user.photo.key,
  width: 150, height: 150, crop: :thumb, gravity: :face, zoom: 0.7, radius: :max %>
  <% end%>
  <h1><%= @user.first_name %>'s Profile Page</h1>
  <%= link_to "Add a new pet", new_pet_path, class: "btn btn-outline-info" %>
  <%= link_to "Update your profile", edit_user_path(@user), class: "btn btn-outline-warning" %>
  <%= link_to "Delete your profile", user_path(@user), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure you want to delete your account?" } %>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col">
        <h2 style = "text-align:center">Your pets</h2>
          <div class = "cards">
            <% @user.pets.each do |pet| %>
              <a href="<%= pet_path(pet)%>">
                <div class = "card" style = "height: 250px" >
                  <% if pet.photos.attached? %>
                    <div class="card-image" style="background-image: url('<%= cl_image_path pet.photos[0].key %>')"></div>
                  <% else %>
                    <div class="card-image" style="background-image: url('')"></div>
                  <% end %>
                  <div class = "card-description" >
                    <h2><%= pet.name %></h2>
                  </div>
                </div>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>


<input name="tab" id="tab2" type="radio" />
<section class="tab-content">
   <h1>My Reservations</h1>
<div class=container>
  <div class="row justify-content-center">
    <div class="col">
      <h3 style = "text-align:center">Received reservations</h3>
      <div class = "cards-reservation">
        <% @user.received_reservations.each do |reservation| %>
          <div class = card >
            <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(reservation.pet.photos[0].key)%>)"></div>
            <div class = "card-description">
              <h2><%= reservation.pet.name %></h2>
              <p>Rented from <%= reservation.start_date %> - <%= reservation.end_date%> by <%= reservation.user.first_name%> <%= reservation.user.last_name%></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col">
      <h3 style = "text-align:center">Sent reservations</h3>
      <div class = "cards-reservation">
        <% @user.sent_reservations.each do |reservation| %>
          <div class = card >
            <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(reservation.pet.photo.key)%>)"></div>
            <div class = "card-description">
              <h2><%= reservation.pet.name %></h2>
              <p>Rented from <%= reservation.start_date %> - <%= reservation.end_date%> by <%= reservation.user.first_name%> <%= reservation.user.last_name%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</section>
<input name="tab" id="tab3" type="radio" />
<section class="tab-content">
   <p> Contents for tab 3 </p>
</section>

app/views/users/show.html.erb
<section class="tabs-container">
   <label for="tab1"> Profile </label>
   <label for="tab2"> Pets I'm borrowing </label>
   <label for="tab3"> Borrow request for my pets </label>
</section>

<input name="tab" id="tab1" type="radio" <%= "checked" if params["tab"].blank?  %>/>
<section class="tab-content">
  <div class="user-banner">
  <% if @user.photo.key.nil?%>
  <%= image_tag '/cat-icon.png',
  width: 150, height: 150, style: "border-radius: 50%" %>
  <% else%>
  <%= cl_image_tag @user.photo.key,
  width: 150, height: 150, crop: :thumb, gravity: :face, zoom: 0.7, radius: :max %>
  <% end%>
  <h1><%= @user.first_name %>'s Profile Page</h1>
  <%= link_to "Add a new pet", new_pet_path, class: "btn btn-info" %>
  <%= link_to "Update your profile", edit_user_path(@user), class: "btn btn-warning" %>
  <%= link_to "Delete your profile", user_path(@user), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete your account?" } %>
</div>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col">
        <h2 style="text-align: center">Your pets</h2>
          <div class = "cards">
            <% @user.pets.each do |pet| %>
              <a href="<%= pet_path(pet)%>">
                <div class = "card card-index" style = "height: 350px" >
                  <% if pet.photos.attached? %>
                    <div class="card-image" style="background-image: url('<%= cl_image_path pet.photos[0].key %>')"></div>
                  <% else %>
                    <div class="card-image" style="background-image: url('')"></div>
                  <% end %>
                  <div class = "card-description" >
                    <h2><%= pet.name %></h2>
                    <p>Breed: <%= pet.breed %></p>
                    <p>Age: <%= pet.age %></p>
                  </div>
                </div>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>


<input name="tab" id="tab2" type="radio" <%= "checked" if params["tab"] == "new-pet-requests" %> />
<section class="tab-content">
<div class=container>
  <div class="row justify-content-center">
    <div class="col">
      <h3 class="reservation-titles">Pending</h3>
        <div class = "cards-reservation">
        <% @user.sent_reservations.each do |reservation| %>
          <%if reservation.status == 'pending'%>
            <div class="card-product">
              <%=cl_image_tag(reservation.pet.photos[0].key)%>
                <div class="card-product-infos">
                <h2><%= reservation.pet.name %></h2>
                <p>Waiting for owner response</p>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>
    <div class="col">
      <h3 class="reservation-titles">Finalised</h3>
      <div class = "cards-reservation">
        <% @user.sent_reservations.each do |reservation| %>
          <%unless reservation.status == 'pending'%>
            <div class="card-product">
              <%=cl_image_tag(reservation.pet.photos[0].key)%>
              <div class="card-product-infos">
                <h2><%= reservation.pet.name %></h2>
                <p>Status <%=reservation.status %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</section>
<input name="tab" id="tab3" type="radio" <%= "checked" if params["tab"] == "borrow-requests" %>/>
<section class="tab-content">
<div class=container>
  <div class="row justify-content-center">
    <div class="col">
      <h3 class="reservation-titles">Pending</h3>
      <div class = "cards-reservation">
        <% @user.received_reservations.each do |reservation| %>
          <%if reservation.status == 'pending'%>
            <div class ="card-product">
              <%=cl_image_tag(reservation.pet.photos[0].key)%>
              <div class="card-product-infos">
                <h2><%= reservation.pet.name %></h2>
                <p><%= reservation.user.first_name%> <%= reservation.user.last_name%> wants to be a petmate from</p>
                <p><%= reservation.start_date %> - <%= reservation.end_date%></p>
                  <div class="d-flex button-div justify-content-end align-items-end card-product-buttons">
                    <%= link_to 'Accept', accept_pet_reservation_path(reservation.pet.id,reservation.id), method: :patch, class: 'btn btn-flat-blue reservation-button' %>
                    <%= link_to 'Decline', reject_pet_reservation_path(reservation.pet.id,reservation.id), method: :patch, class: 'btn btn-flat-red reservation-button' %>
                  </div>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>

    <div class="col">
      <h3 class="reservation-titles">Resolved</h3>
      <div class = "cards-reservation">
        <% @user.received_reservations.each do |reservation| %>
          <%unless reservation.status == 'pending'%>
            <div class="card-product">
            <%=cl_image_tag(reservation.pet.photos[0].key)%>
            <div class="card-product-infos">
                <h2><%= reservation.pet.name %></h2>
                <p>Status: <%=reservation.status %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>
</section>